library(tidyverse)
library(ggplot2)
library(ggpubr)
sink("analysis.txt")
count <- function(c){
  if (is.na(table(npSearchData$balanced)["TRUE"])){
    return (0)
  }
  else{
    return (table(npSearchData$balanced)["TRUE"])
  }
}
searchdf <- read.csv("C:/Users/trip9/Google Drive/DSU/CSC/CSC 786 Cyber Problems/Code/treap_search_file.txt", header <- FALSE)
insertionData <- read.csv('C:/Users/trip9/Google Drive/DSU/CSC/CSC 786 Cyber Problems/Code/insertion_output.txt')
deletionData <- read.csv('C:/Users/trip9/Google Drive/DSU/CSC/CSC 786 Cyber Problems/Code/deletion_output.txt')
finalData <- read.csv('C:/Users/trip9/Google Drive/DSU/CSC/CSC 786 Cyber Problems/Code/final_output.txt')
nSearchData <- read.csv('C:/Users/trip9/Google Drive/DSU/CSC/CSC 786 Cyber Problems/Code/n_search_output.txt')
npSearchData <- read.csv('C:/Users/trip9/Google Drive/DSU/CSC/CSC 786 Cyber Problems/Code/np_search_output.txt')
psSearchData <- read.csv('C:/Users/trip9/Google Drive/DSU/CSC/CSC 786 Cyber Problems/Code/ps_search_output.txt')
pspSearchData <- read.csv('C:/Users/trip9/Google Drive/DSU/CSC/CSC 786 Cyber Problems/Code/psp_search_output.txt')

insertionData$balanced <- ifelse(insertionData$balance >= -1 && insertionData$balance <= 1,TRUE,FALSE)
deletionData$balanced <- ifelse(deletionData$balance >= -1 && deletionData$balance <= 1,TRUE,FALSE)
nSearchData$balanced <- ifelse(nSearchData$balance >= -1 && nSearchData$balance <= 1,TRUE,FALSE)
npSearchData$balanced <- ifelse(npSearchData$balance >= -1 && npSearchData$balance <= 1,TRUE,FALSE)
psSearchData$balanced <- ifelse(psSearchData$balance >= -1 && psSearchData$balance <= 1,TRUE,FALSE)
pspSearchData$balanced <- ifelse(pspSearchData$balance >= -1 && pspSearchData$balance <= 1,TRUE,FALSE)
insertionData$time <- as.integer(insertionData$time)
deletionData$time <- as.integer(deletionData$time)
nSearchData$time <- as.integer(nSearchData$time)
npSearchData$time <- as.integer(npSearchData$time)
psSearchData$time <- as.integer(psSearchData$time)
pspSearchData$time <- as.integer(pspSearchData$time)

print("Number of Rotations:")
cat("        Insertion Total: ", sum(insertionData$num_rotations), "\n")
cat("        Insertion Average: " , mean(insertionData$num_rotations), "\n")
cat("        Deletion Total: " , sum(deletionData$num_rotations), "\n")
cat("        Deletion Average: " , mean(deletionData$num_rotations), "\n")
cat("        New Priority Search Total: " , sum(npSearchData$num_rotations), "\n")
cat("        New Priority Search Average: " , mean(npSearchData$num_rotations), "\n")
cat("        Swap Parent Search Total: " , sum(psSearchData$num_rotations), "\n")
cat("        Swap Parent Search Average: " , mean(psSearchData$num_rotations), "\n")
cat("        Swap Parent with Probability Search Total: " , sum(pspSearchData$num_rotations), "\n")
cat("        Swap Parent with Probability Search Average: " , mean(pspSearchData$num_rotations), "\n")


print("Operation Times:")
cat("        Insertion Total: " , sum(insertionData$time), "\n")
cat("        Insertion Average: " , mean(insertionData$time), "\n")
cat("        Deletion Total: " , sum(deletionData$time), "\n")
cat("        Deletion Average: " , mean(deletionData$time), "\n")
cat("        Normal Search Total: " , sum(nSearchData$time), "\n")
cat("        Normal Search Average: " , mean(nSearchData$time), "\n")
cat("        New Priority Search Total: " , sum(npSearchData$time), "\n")
cat("        New Priority Search Average: " , mean(npSearchData$time), "\n")
cat("        Swap Parent Search Total: " , sum(psSearchData$time), "\n")
cat("        Swap Parent Search Average: " , mean(psSearchData$time), "\n")
cat("        Swap Parent with Probability Search Total: " , sum(pspSearchData$time), "\n")
cat("        Swap Parent with Probability Search Average: " , mean(pspSearchData$time), "\n")

print("Balance Factors:")
cat("        Insertion Average: " , mean(insertionData$balance), "\n")
cat("        Insertion Balance %: " , count(insertionData), "\n")
cat("        Deletion Average: " , mean(deletionData$balance), "\n")
cat("        Deletion Balance %: " , count(deletionData), "\n")
cat("        Normal Search Average: " , mean(nSearchData$balance), "\n")
cat("        Normal Search Balance %: " , count(nSearchData), "\n")
cat("        New Priority Search Average: " , mean(npSearchData$balance), "\n")
cat("        New Priority Search Balance %: " , count(npSearchData), "\n")
cat("        Swap Parent Search Average: " , mean(psSearchData$balance), "\n")
cat("        Swap Parent Search Balance %: " , count(psSearchData), "\n")
cat("        Swap Parent with Probability Search Average: " , mean(pspSearchData$balance), "\n")
cat("        Swap Parent with Probability Search Balance %: " , count(pspSearchData), "\n")

print("Treap Heights:")
cat("        Insertion Average: " , mean(insertionData$height), "\n")
cat("        Deletion Average: " , mean(deletionData$height), "\n")
cat("        Normal Search Average: " , mean(nSearchData$height), "\n")
cat("        New Priority Search Average: " , mean(npSearchData$height), "\n")
cat("        Swap Parent Search Average: " , mean(psSearchData$height), "\n")
cat("        Swap Parent with Probability Search Average: " , mean(pspSearchData$height), "\n")

most_common <- names(sort(table(searchdf$V1), decreasing=TRUE))[1]
cat("Ending level for most common item ", most_common, "\n")
print(filter(finalData, value == most_common))

sink()

operations <- c("Deletion", "Insertion", "New Priority Search", "Parent Swap Search", "Parent Swap with Probability")
num_of_rotations <-c(c(sum(deletionData$num_left_rotations),sum(deletionData$num_right_rotations)), c(sum(insertionData$num_left_rotations),sum(insertionData$num_right_rotations)),c(sum(npSearchData$num_left_rotations),sum(npSearchData$num_right_rotations)),c(sum(psSearchData$num_left_rotations),sum(psSearchData$num_right_rotations)),c(sum(pspSearchData$num_left_rotations),sum(pspSearchData$num_right_rotations)))
rotation_type <- rep(c("Left","Right"), 5)
data <- data.frame(operations, num_of_rotations, rotation_type)
ggplot(data, aes(fill = rotation_type, x = operations, y = num_of_rotations )) + geom_bar(position = "stack", stat = "identity") + xlab("Operations") + ylab("Number of Rotations") + ggtitle("Total Rotations per Operation")

num_of_rotations <-c(c(mean(deletionData$num_left_rotations),mean(deletionData$num_right_rotations)), c(mean(insertionData$num_left_rotations),mean(insertionData$num_right_rotations)),c(mean(npSearchData$num_left_rotations),mean(npSearchData$num_right_rotations)),c(mean(psSearchData$num_left_rotations),mean(psSearchData$num_right_rotations)),c(mean(pspSearchData$num_left_rotations),mean(pspSearchData$num_right_rotations)))
data <- data.frame(operations, num_of_rotations, rotation_type)
ggplot(data, aes(fill = rotation_type, x = operations, y = num_of_rotations )) + geom_bar(position = "stack", stat = "identity") + xlab("Operations") + ylab("Number of Rotations") + ggtitle("Average Rotations per Operation")

labels <- c("Deletion", "Insertion", "Normal Search", "New Priority Search", "Parent Swap Search", "Parent Swap with Probability")
times <- c(mean(deletionData$time, na.rm = TRUE), mean(insertionData$time, na.rm = TRUE), mean(nSearchData$time, na.rm = TRUE), mean(npSearchData$time, na.rm = TRUE), mean(psSearchData$time, na.rm = TRUE), mean(pspSearchData$time, na.rm = TRUE))
data <- data.frame(labels, times)
ggplot(data, aes(x = labels, y = times)) + geom_bar(stat="identity") + xlab("Operations") + ylab("Time in ns")+ggtitle("Average Operation Time")

nSearchDataSelection <- slice_sample(nSearchData, n = 10)
npSearchDataSelection <- slice_sample(npSearchData, n = 10)
psSearchDataSelection <- slice_sample(psSearchData, n = 10)
pspSearchDataSelection <- slice_sample(pspSearchData, n = 10)

ys <- c(nSearchDataSelection$height, npSearchDataSelection$height, psSearchDataSelection$height, pspSearchDataSelection$height)
xs <- c(nSearchDataSelection$balance, npSearchDataSelection$balance, psSearchDataSelection$balance, pspSearchDataSelection$balance)
categories <- c( rep("Normal", 10), rep("New Priority", 10), rep("Swap Priority", 10), rep("Swap Priority with Probability", 10))
data <- data.frame(xs,ys,categories)
ggplot(data, aes(x=xs, y=ys, color = categories)) + geom_point() + xlab("Balance Factor") + ylab("Height") + ggtitle("Height vs Balance")